version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - ./data/:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=bot
      - MYSQL_PASSWORD=qwer1234t5
      - MYSQL_ROOT_PASSWORD=qwer1234t5 
      - MYSQL_DATABASE=bot_db
